# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, test and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
  
  deploy:

    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy to Cloud storage
        uses: abinmn/gcp-storage-bucket-action@v1.0
        with:
          service_key: ${{ secrets.GCP_SERVICE_KEY }}
          project: ${{ secrets.GCP_PROJECT }}
          bucket_name: ${{ secrets.GCP_BUCKET_NAME }}
          home_page_path: index.html
          error_page_path: index.html
          build_folder: ${{ github.workspace }}/build
